### ISSUE TITLE
error with version check?

### ISSUE THREAD

**Issue by WildlandsDev** [Lanzaned-Enterprises/LENT-GovernmentJob#2]
when I run latest build I get this error;

[script:LENT-Governme] SCRIPT ERROR: @LENT-GovernmentJob/server/sv_versioncheck.lua:31: attempt to compare string with number
[script:LENT-Governme] > userCallback (@LENT-GovernmentJob/server/sv_versioncheck.lua:31)

**Comment by SerenaKing** [comment]
I will check it out here in a second.

**Comment by SerenaKing** [comment]
This is now been fixed with the latest push. Redownload the server file responsible for this action..

**Comment by Nathant995** [comment]
thanks!
appreciate the hard work! found this resource really helpful!
