### ISSUE TITLE
sv_versioncheck 

### ISSUE THREAD

**Issue by WildlandsDev** [Lanzaned-Enterprises/LENT-GovernmentJob#3]
[script:LENT-Governme] SCRIPT ERROR: @LENT-GovernmentJob/server/sv_versioncheck.lua:31: attempt to compare string with number
[script:LENT-Governme] > userCallback (@LENT-GovernmentJob/server/sv_versioncheck.lua:31)

hey just fyi!

**Comment by SerenaKing** [comment]
Seems that the link used isn't the right one. Currently attempting to fix the issue.

**Comment by SerenaKing** [comment]
Fixed with push of [8964f70](https://github.com/Lanzaned-Enterprises/LENT-GovernmentJob/commit/8964f70e4aa442cf225c470deb3ff58c0f16acb8)
