### ISSUE TITLE
Duty on and off? and missing weapons in armory?

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Lanzaned-Enterprises/LENT-GovernmentJob#4]
1. How can i sign on and off duty????

2. Missing weapons?
![image](https://user-images.githubusercontent.com/35656492/225448157-aa3cbd07-3560-43ac-a245-4b799684b066.png)

**Comment by SerenaKing** [comment]
Hello, @AndreasFromDanmark 

When it comes to duty zones / peds you will have to create them yourself. As the readme says this resource is not just plug & play some knowledge is required and yourself or your team need to setup the right coordinates and locations for the peds to spawn & work.

You can follow the examples given in the `LENT-GovernmentJob/Functions/*.lua`

- Serena

**Comment by SerenaKing** [comment]
Nothing is "missing" from the armory either you will need to specify the weapons for your armory in your config files. When I created the resource it used / uses custom weapons which are the blank spots along with respective bullet types.

**Comment by AndreasFromDanmark** [comment]
@SerenaKing I like the idea for this script, but it will be nice if you could create the "zones/peds", and then people could move them where they need to be with the coords.

Make the script plug & play

**Comment by SerenaKing** [comment]
You can create the zones & peds yourself? I can't make this script "Plug & Play" Because of how many variety there is in stations, locations etc

**Comment by AndreasFromDanmark** [comment]
@SerenaKing Can you give me a template for create a zone and peds? then 🤔

**Comment by SerenaKing** [comment]
https://github.com/Lanzaned-Enterprises/LENT-GovernmentJob/blob/main/functions/cl_zones.lua#L12

**Comment by AndreasFromDanmark** [comment]
Is this right?
![image](https://user-images.githubusercontent.com/35656492/225783857-eea4db35-77a4-41b0-a04d-82b4e02bd03c.png)

**Comment by SerenaKing** [comment]
Yea

**Comment by AndreasFromDanmark** [comment]
Yeah i cant get that to work 🤔

**Comment by SerenaKing** [comment]
Yea the line 20 job part is wrong. there's a different method to call for multiple departments.
`{ ['police'] = 0, ['bcso'] = 0, ['sasp'] = 0, },` 
as example

**Comment by AndreasFromDanmark** [comment]
Yeah that doesn't work either, but when i create a "peds" it works fine. But i dont want to have peds stands around the map.

![image](https://user-images.githubusercontent.com/35656492/226110276-9580b216-a980-4ac3-95cf-a218510ff17d.png)

And i have the right police job
![image](https://user-images.githubusercontent.com/35656492/226110390-0603df76-da04-40d2-949d-d9daffe734fb.png)

**Comment by SerenaKing** [comment]
🤦 Offcourse it won't work. You need to actually fill the data of the polyzone 😆 You've left the coordinates, Heading, Width, Height and all that on 0.. use `/pzcreate box duty 1 1` and look into how to use polyzone.

**Comment by AndreasFromDanmark** [comment]
Now im getting a problem with the vehicle spawner, i change LENT-Menu to qb-menu

![image](https://user-images.githubusercontent.com/35656492/226117541-830d8259-3b10-4cce-85ad-16a71abcb770.png)

**Comment by SerenaKing** [comment]
That I don't know about. Vehicle spawner either as my own menu or as qb-menu. I'm also closing this issue since it's no longer related to the issue that was presented at first. If you want more help I'd recommand you join the discord

[Discord Server](https://discord.lanzaned.com/)
